spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: project
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: project
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    table: project_schema_version
    baseline-version: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: ${MAILTRAP_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAILTRAP_PORT:2525}
    username: ${MAILTRAP_USERNAME:}
    password: ${MAILTRAP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

vars:
  security:
    enable: true

server:
  port: 8090

token:
  ttl: 3600000
  secret: "https://www.youtube.com/watch?v=VBUMYOYJISc"

mail:
  from: ${MAIL_FROM:no-reply@nutrivision.local}

admin:
  username: admin
  email: admin@admin.com
  password: admin

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.security: INFO



